<?php

/**
 * @file
 * This is a über module!
 *
 * THIS IS FOR NODES AND NOT ENTITIES, BECAUSE ENTITY API SUCKS IN BOTH CORE
 * AND CONTRIB. CORE HAD A GOOD IDEA WHILE CONTRIB KILLED IT.
 *
 * In Drupal 8 I don't know if this will be a needed module but this will be
 * easier to implement because everything will be mutualized at the Entity API
 * level and we would not need node type exceptions.
 */

/**
 * View mode name.
 */
const NODEBLOCK_VIEW_MODE         = 'nodeblock';

/**
 * Default cache mode.
 */
const NODEBLOCK_CACHE_DEFAULT     = DRUPAL_CACHE_PER_PAGE;

/**
 * Cache mode variable name.
 */
const NODEBLOCK_CACHE_VAR         = 'nodeblock_block_cache';

/**
 * Node block enabled node types variable.
 */
const NODEBLOCK_VAR_TYPES         = 'nodeblock_enabled_types';

/**
 * Display node action links variable.
 */
const NODEBLOCK_VAR_DISPLAY_LINKS = 'nodeblock_display_links';

/**
 * Display node action links default value.
 */
const NODEBLOCK_DEF_DISPLAY_LINKS = true;

/**
 * Implements hook_permission().
 */
function nodeblock_permission() {
  return array(
    'create node block' => array(
      'title'       => t("Create node blocks"),
      'description' => t("With this permission, users can create blocks for their nodes. Per node permission will be determined following node access rights."),
    ),
  );
}

/**
 * Node type is enabled for having block.
 *
 * @param string $type
 *   Node type
 *
 * @return boolean
 *   True or false.
 */
function nodeblock_node_type_is_enabled($type) {
  return !($types = variable_get(NODEBLOCK_VAR_TYPES, NULL)) || empty($types) || (isset($types[$type]) && $types[$type]);
}

/**
 * Tell if the given node has a block.
 *
 * @param object $node
 *   Node object.
 *
 * @return boolean
 *   True if node has a bloc false else.
 */
function nodeblock_node_has_block($node) {
  // @todo EXCESSIVE QUERY SPOTTED!!!
  return (bool)db_query("SELECT 1 FROM {nodeblock} WHERE nid = :nid", array(':nid' => $node->nid))->fetchField();
}

/**
 * Menu access helper.
 */
function nodeblock_create_access($node) {
  return variable_get(NODEBLOCK_VAR_DISPLAY_LINKS, NODEBLOCK_DEF_DISPLAY_LINKS) && user_access('create node block') && node_access('update', $node) && !nodeblock_node_has_block($node);
}

/**
 * Menu access helper.
 */
function nodeblock_edit_access($node) {
  return variable_get(NODEBLOCK_VAR_DISPLAY_LINKS, NODEBLOCK_DEF_DISPLAY_LINKS) && user_access('create node block') && node_access('update', $node) && nodeblock_node_has_block($node);
}

/**
 * Menu access helper.
 */
function nodeblock_remove_access($node) {
  return variable_get(NODEBLOCK_VAR_DISPLAY_LINKS, NODEBLOCK_DEF_DISPLAY_LINKS) && user_access('create node block') && node_access('update', $node) && nodeblock_node_has_block($node);
}

/**
 * Implements hook_menu().
 */
function nodeblock_menu() {
  $îtems = array();

  $items['node/%node/create-block'] = array(
    'title'            => "Create block",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nodeblock_create_form', 1),
    'access callback'  => 'nodeblock_create_access',
    'access arguments' => array(1),
    'type'             => MENU_LOCAL_ACTION,
    'file'             => 'nodeblock.pages.inc',
  );
  $items['node/%node/edit-block'] = array(
    'title'            => "Edit block",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nodeblock_create_form', 1),
    'access callback'  => 'nodeblock_edit_access',
    'access arguments' => array(1),
    'type'             => MENU_LOCAL_ACTION,
    'file'             => 'nodeblock.pages.inc',
  );
  $items['node/%node/remove-block'] = array(
    'title'            => "Delete block",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nodeblock_remove_form', 1),
    'access callback'  => 'nodeblock_remove_access',
    'access arguments' => array(1),
    'type'             => MENU_LOCAL_ACTION,
    'file'             => 'nodeblock.pages.inc',
  );

  $items['admin/config/content/nodeblock'] = array(
    'title'            => "Node blocks",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nodeblock_admin_form'),
    'access arguments' => array('administer site configuration'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'nodeblock.admin.inc',
    'description'      => "Configure basic node blocks behavior, features and content type restrictions.",
  );
  $items['admin/reports/nodeblock'] = array(
    'title'            => "Node block list",
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('nodeblock_admin_reports_form'),
    'access arguments' => array('administer site configuration'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'nodeblock.admin.inc',
    'description'      => "List all known node blocks and audit the system.",
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function nodeblock_block_info() {

  // @todo Should we cache this somewhere?
  $query = db_select('nodeblock', 'nb');
  $query->join('node', 'n', 'n.nid = nb.nid');
  $query->addField('n', 'title', 'node_title');
  $records = $query
    ->fields('nb')
    ->execute()
    ->fetchAll();

  // You still can use hook_block_info_alter() to change this manually.
  $cachemode = variable_get(NODEBLOCK_CACHE_VAR, NODEBLOCK_CACHE_DEFAULT);

  $info = array();
  foreach ($records as $data) {

    if ($data->info) {
      $title = check_plain($data->info);
    } else if ($data->title && '<none>' !== $data->title) {
      $title = check_plain($data->title);
    } else {
      $title = check_plain($data->node_title);
    }

    $info[$data->delta] = array(
      'info'  => $title,
      'cache' => $cachemode,
    );
  }

  return $info;
}

/**
 * Implements hook_entity_info_alter().
 */
function nodeblock_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes'][NODEBLOCK_VIEW_MODE]['label'] = t("Node as block");
  $entity_info['node']['view modes'][NODEBLOCK_VIEW_MODE]['custom settings'] = TRUE;
}

/**
 * Implements hook_block_view().
 */
function nodeblock_block_view($delta) {

  global $language;

  $query = "SELECT nid, title FROM {nodeblock} WHERE delta = :delta";
  $data  = db_query($query, array(':delta' => $delta))->fetchObject();

  if ($data && $data->nid && ($node = node_load($data->nid)) && node_access('view', $node)) {

    // Handle gracefully multilingual sites.
    if (drupal_multilingual() && $node->language !== $language->language && $node->tnid) {

      $found = FALSE;

      if (module_exists('translation') && ($translations = translation_node_get_translations($node->tnid))) {
        foreach ($translations as $translation) {
          if ($translation->language === $language->language) {
            // Ensure the user can read the translation.
            if (($translation = node_load($translation->nid)) && node_access('view', $translation)) {
              $found = TRUE;

              $node = $translation;
            }

            // Whatever happens, only one node can exist per language,
            // and we found it.
            continue;
          }
        }
      }

      if (!$found) {
        // Cannot display the block if the languages don't match.
        return;
      }
    }

    if ('<none>' === $data->title) {
      return array(
        'content' => node_view($node, NODEBLOCK_VIEW_MODE),
      );
    } else {
      return array(
        'subject' => empty($data->title) ? $node->title : $data->title,
        'content' => node_view($node, NODEBLOCK_VIEW_MODE),
      );
    }
  }
}
